import styled from "styled-components";
import {
  space,
  display,
  position,
  top,
  bottom,
  left,
  right,
  width,
  minWidth,
  maxWidth,
  fontSize,
  fontFamily,
  color,
  borders,
  flex,
  order,
  alignSelf,
  height,
  maxHeight,
  minHeight,
  textAlign,
  alignItems,
  alignContent,
  justifyContent,
  flexWrap,
  flexBasis,
  flexDirection,
  justifySelf,
  overflow,
  verticalAlign,
  zIndex
} from "styled-system";

const Box = styled("div")(
  {
    boxSizing: "border-box",
    // kill margin-collapse to allow us to couple negative margins
    overflow: "visible",
    "-webkit-overflow-scrolling": "touch"
  },
  space,
  display,
  position,
  top,
  bottom,
  left,
  right,
  minWidth,
  maxWidth,
  width,
  fontSize,
  fontFamily,
  textAlign,
  color,
  borders,
  flex,
  order,
  alignSelf,
  height,
  minHeight,
  maxHeight,
  alignItems,
  alignContent,
  justifyContent,
  flexWrap,
  flexBasis,
  flexDirection,
  justifySelf,
  verticalAlign,
  zIndex,
  overflow
);

Box.displayName = "Box";

Box.propTypes = {
  ...space.propTypes,
  ...display.propTypes,
  ...position.propTypes,
  ...top.propTypes,
  ...bottom.propTypes,
  ...left.propTypes,
  ...right.propTypes,
  ...minWidth.propTypes,
  ...maxWidth.propTypes,
  ...width.propTypes,
  ...fontSize.propTypes,
  ...fontFamily.propTypes,
  ...textAlign.propTypes,
  ...color.propTypes,
  ...borders.propTypes,
  ...flex.propTypes,
  ...order.propTypes,
  ...alignSelf.propTypes,
  ...height.propTypes,
  ...minHeight.propTypes,
  ...maxHeight.propTypes,
  ...alignItems.propTypes,
  ...alignContent.propTypes,
  ...justifyContent.propTypes,
  ...flexWrap.propTypes,
  ...flexBasis.propTypes,
  ...flexDirection.propTypes,
  ...justifySelf.propTypes,
  ...verticalAlign.propTypes,
  ...zIndex.propTypes,
  ...overflow.propTypes
};

export default Box;
